mondeja/leptos-fluent

README.md, examples/complete/src/main.rs, examples/minimal/src/main.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml
=> Add `provide_context` parameter to `leptos_fluent!`

CONTRIBUTING.md, Cargo.toml, README.md, examples/complete/src/lib.rs, examples/minimal/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Add `tr!` and `move_tr!` macros

leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/languages.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml
=> Sort detected languages in locales folder by language name

.github/workflows/ci.yml, .github/workflows/update-copyright-years.yml, .gitignore, .pre-commit-config.yaml
Also add workflow to update copyright years and improve Prettier pre-commit hook performance.
Closes #27
=> Create releases on tags push

.github/workflows/ci.yml, leptos-fluent/Cargo.toml
=> Use local leptos-fluent-macros and update version on release

.github/workflows/ci.yml, Cargo.toml
=> Test on Windows and MacOS

CHANGELOG.md, examples/ssr-hydrate-actix/Cargo.toml, leptos-fluent/Cargo.toml
=> Set leptos to `>=0.6`

CHANGELOG.md, Cargo.lock, README.md, end2end/tests/csr_complete.rs, examples/csr-complete/src/lib.rs, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Rename `set_to_localstorage` as `set_language_to_localstorage`

.github/workflows/ci.yml, .github/workflows/pre-commit-autoupdate.yml, .pre-commit-config.yaml, Cargo.lock, Cargo.toml, end2end/.pre-commit-config.yaml, end2end/Cargo.toml, end2end/tests-helpers/Cargo.toml, end2end/tests-helpers/src/lib.rs, examples/ssr-hydrate-actix/Cargo.toml, examples/ssr-hydrate-actix/src/main.rs, examples/ssr-hydrate-axum/Cargo.toml, examples/ssr-hydrate-axum/src/error_template.rs, examples/ssr-hydrate-axum/src/main.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent/Cargo.toml
=> Update pre-commit Rust tooling

CHANGELOG.md, CONTRIBUTING.md, Cargo.lock, README.md, end2end/tests/TODO.md, end2end/tests/csr_complete.rs, examples/csr-complete/src/lib.rs, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs, leptos-fluent/src/url.rs
Also rename URL param macro parameters.
=> Add `set_language_to_url_param` macro parameter

CHANGELOG.md, Cargo.lock, README.md, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/cookie.rs, leptos-fluent/src/lib.rs, leptos-fluent/src/localstorage.rs, leptos-fluent/src/url.rs
=> Add cookie support

CHANGELOG.md, README.md, examples/csr-complete/src/lib.rs, examples/csr-minimal/src/lib.rs, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Drop `I18n` implementation

CHANGELOG.md, Cargo.lock, README.md, leptos-fluent-macros/Cargo.toml, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Fix trait not in scope for translation macros

CHANGELOG.md, Cargo.lock, README.md, end2end/tests/TODO.md, leptos-fluent-macros/Cargo.toml, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/cookie.rs, leptos-fluent/src/lib.rs
=> Fix error setting cookies

CHANGELOG.md, Cargo.lock, README.md, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent-macros/src/translations_checker/fluent_entries.rs, leptos-fluent-macros/src/translations_checker/mod.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Track locale and language files

CHANGELOG.md, Cargo.lock, README.md, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/files_tracker.rs, leptos-fluent-macros/src/fluent_resources.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent-macros/src/translations_checker/fluent_entries.rs, leptos-fluent-macros/src/translations_checker/mod.rs, leptos-fluent-macros/src/translations_checker/tr_macros.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Report Fluent syntax errors

.github/workflows/ci.yml
=> Retry end2end tests on CI

leptos-fluent-macros/src/languages.rs, leptos-fluent-macros/src/loader.rs
=> Raise syn error instead of panic reading languages file

CHANGELOG.md, Cargo.lock, README.md, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/languages.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Allow to read languages from a JSON5 file

CHANGELOG.md, Cargo.lock, README.md, examples/csr-minimal/Cargo.toml, examples/csr-minimal/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/files_tracker.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent-macros/src/translations_checker/fluent_entries.rs, leptos-fluent-macros/src/translations_checker/mod.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Add `core_locales` argument to `leptos_fluent!` macro

CHANGELOG.md, leptos-fluent-macros/src/translations_checker/mod.rs, leptos-fluent-macros/src/translations_checker/tr_macros.rs
=> Notify invalid Fluent message identifiers checking translations

README.md, examples/ssr-hydrate-actix/Cargo.toml, examples/ssr-hydrate-axum/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Document how to watch Fluent files with cargo-leptos

CHANGELOG.md, Cargo.lock, README.md, end2end/tests/TODO.md, end2end/tests/csr_complete.rs, examples/csr-complete/locales/en/main.ftl, examples/csr-complete/locales/es/main.ftl, examples/csr-complete/locales/languages.json, examples/csr-complete/src/lib.rs, examples/ssr-hydrate-actix/Cargo.toml, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/Cargo.toml, examples/ssr-hydrate-axum/locales/languages.yaml, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/languages.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Add `sync_html_tag_dir` parameter to `leptos_fluent!` macro

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, book/src/checking-translations.md, examples/csr-complete/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/cookie.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/Cargo.toml
=> Validate cookie attributes when defined using string literals

.gitignore, CHANGELOG.md, book/src/strategies.md, end2end/tests/TODO.md, end2end/tests/url_param_to_cookie.rs, examples/csr-complete/src/lib.rs, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs
=> Add `initial_language_from_url_param_to_cookie` to `leptos_fluent!`

.github/actions/get-toolchain/action.yml, .github/workflows/ci.yml, CHANGELOG.md, examples/csr-complete/Cargo.toml, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/translations_checker/mod.rs, leptos-fluent-macros/src/translations_checker/tr_macros.rs, leptos-fluent/Cargo.toml, rust-toolchain.toml
=> Show locations of `tr!` macro spans when using a new `nightly` feature

Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Don't use web_sys from leptos

CHANGELOG.md, book/src/basic-usage.md, leptos-fluent/src/lib.rs, rust-toolchain.toml
=> Allow to call the i18n context on nightly

Cargo.lock, book/src/faqs.md, examples/ssr-hydrate-actix/locales/en/main.ftl, examples/ssr-hydrate-actix/locales/es/main.ftl, examples/ssr-hydrate-actix/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/translations_checker/tr_macros.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Add server action example

CHANGELOG.md, book/src/strategies.md, end2end/tests/TODO.md, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs
=> Add `initial_language_from_navigator_to_localstorage` to `leptos_fluent!`

CHANGELOG.md, book/src/strategies.md, end2end/tests/TODO.md, examples/ssr-hydrate-actix/src/app.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs
=> Add `initial_language_from_navigator_to_cookie` to `leptos_fluent!`

CHANGELOG.md, Cargo.lock, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Add `SsrHtmlTag` component

book/src/basic-usage.md, book/src/checking-translations.md, book/src/faqs.md, book/src/install.md, book/src/strategies.md, examples/ssr-hydrate-actix/Cargo.toml, leptos-fluent-macros/src/loader.rs
=> Raise better error using `#[cfg( ... )]` before macro parameters

CHANGELOG.md, book/src/strategies.md, end2end/tests/TODO.md, examples/ssr-hydrate-actix/src/app.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/src/lib.rs
- `initial_language_from_server_function`
- `set_language_to_server_function`
=> Add server functions parameters to `leptos_fluent!`

CHANGELOG.md, Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/loader.rs, leptos-fluent-macros/tests/ui/leptos_fluent/fail/empty_parameter.stderr, leptos-fluent-macros/tests/ui/leptos_fluent/pass/struct_field_init_shorthand.rs, leptos-fluent/Cargo.toml
=> Allow struct field init shorthand for most macro parameters

CHANGELOG.md, Cargo.lock, book/src/faqs.md, examples/system-gtk/src/main.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent-macros/tests/ui/leptos_fluent/pass/multiple_cfg_conditional_cheks.rs, leptos-fluent/Cargo.toml
=> Accept multiple config conditional checks for the same parameters

CHANGELOG.md, Cargo.lock, book/book.toml, book/src/faqs.md, book/src/leptos_fluent.md, book/src/strategies.md, end2end/tests/TODO.md, end2end/tests/url_param.rs, end2end/tests/url_param_to_cookie.rs, end2end/tests/url_param_to_localstorage.rs, examples/ssr-hydrate-actix/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs, leptos-fluent/src/url.rs
=> Initial language from URL path

CHANGELOG.md, Cargo.lock, examples/csr-minimal/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml
=> Fix bug discovering initial language from `navigator.languages`

.pre-commit-config.yaml, CHANGELOG.md, Cargo.lock, book/src/faqs.md, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Deprecate `SsrHtmlTag` component

CHANGELOG.md, Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml
=> Fix syntax error at `leptos_fluent!` macro expansion on SSR

CHANGELOG.md, Cargo.lock, README.md, book/src/install.md, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/languages.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Add `debug` feature

CHANGELOG.md, Cargo.lock, book/src/leptos_fluent.md, book/src/strategies.md, end2end/tests/TODO.md, examples/csr-complete/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Sync browser language with client

CHANGELOG.md, Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent/Cargo.toml
=> Relax fluent-templates version

CHANGELOG.md, CONTRIBUTING.md, Cargo.lock, book/src/basic-usage.md, book/src/faqs.md, end2end/tests/context_outside_reactive_ownership_tree.rs, examples/csr-complete/src/lib.rs, examples/csr-minimal/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/translations_checker/tr_macros.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Alternative to panicking outside reactive ownership tree

CHANGELOG.md, Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/tests/ui/leptos_fluent/pass/empty_translations.rs, leptos-fluent/Cargo.toml
=> Allow to pass empty `translations` array to `leptos_fluent!`

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, README.md, book/src/basic-usage.md, book/src/install.md, end2end/Cargo.toml, examples/csr-complete/Cargo.toml, examples/csr-minimal/Cargo.toml, examples/ssr-hydrate-actix/Cargo.toml, examples/ssr-hydrate-axum/Cargo.toml, examples/ssr-hydrate-axum/src/fileserv.rs, examples/ssr-islands-axum/Cargo.toml, examples/ssr-islands-axum/src/app.rs, examples/ssr-islands-axum/src/fileserv.rs, examples/system-gtk/Cargo.toml, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/Cargo.toml, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Let rustc infer literal booleans in `leptos_fluent!`

Cargo.lock, README.md, book/src/basic-usage.md, book/src/install.md, leptos-fluent/README.md, leptos-fluent/src/lib.rs
=> Update docs to use fluent-templates v0.12

book/src/faqs.md, book/src/languages.md
=> Document language names inference logic

.github/workflows/ci.yml, CHANGELOG.md, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/translations_checker/fluent_entries.rs
=> Fix Fluent message references not recognized by translations checker

CHANGELOG.md, Cargo.lock, book/src/leptos_fluent.md, examples/csr-minimal/src/lib.rs, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/fluent_entries.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent-macros/src/tr_macros.rs, leptos-fluent-macros/src/translations_checker/mod.rs, leptos-fluent-macros/src/translations_filler/mod.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
=> Add new parameter `fill_translations` to `leptos_fluent!`

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, Cargo.toml, book/src/leptos_fluent.md, book/src/strategies.md, examples/csr-complete/src/lib.rs, examples/csr-minimal/src/lib.rs, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/src/lib.rs, leptos-fluent/src/sessionstorage.rs, tests/end2end/TODO.md, tests/end2end/set-language-to-sessionstorage/Cargo.toml, tests/end2end/set-language-to-sessionstorage/tests/set_language_to_localstorage.rs, tests/end2end/set-language-to-sessionstorage/webdriver.json, tests/end2end/tests/localstorage_to_sessionstorage.rs, tests/end2end/tests/sessionstorage.rs, tests/end2end/tests/sessionstorage_to_cookie.rs, tests/end2end/tests/sessionstorage_to_localstorage.rs
=> Add minimal implementation for session storages

CHANGELOG.md, book/src/leptos_fluent.md, book/src/strategies.md, examples/csr-complete/src/lib.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent-macros/src/loader.rs, leptos-fluent/src/lib.rs, tests/end2end/TODO.md
=> Add missing parameters for session storage management

examples/ssr-hydrate-axum/src/main.rs
=> Refactor Axum example

CHANGELOG.md, Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/tr_macros.rs, leptos-fluent/Cargo.toml, leptos-fluent/src/lib.rs
And fix a minor bug in error message.
=> Reduce allocations in source parser of translations checker

.github/workflows/ci.yml
- `/next` (master)
- `/latest` (latest version released)
- `/v{version}` (specific version)
=> Better book releasing strategy

CHANGELOG.md, book/src/advanced-usage.md, book/src/basic-usage.md, book/src/faqs.md, book/src/install.md, examples/csr-complete/src/lib.rs, examples/ssr-hydrate-actix/src/app.rs, examples/ssr-hydrate-axum/src/app.rs, leptos-fluent-macros/src/lib.rs, leptos-fluent/src/lib.rs, tests/end2end/tests/csr_minimal.rs
=> Deprecate `Language`'s methods `is_active` and `activate`

.github/workflows/ci.yml, CHANGELOG.md, Cargo.lock, leptos-fluent-macros/Cargo.toml, leptos-fluent-macros/src/lib.rs, leptos-fluent/Cargo.toml
=> Fix `actix_web::HttpRequest` not longer provided in context
